#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")/.."

TOTAL_STAGES=8

banner "GitHub App für den Release-Log-Hub"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Umgebung und Basis-URL"
say "Es gibt zwei Apps: eine für den Spike am Tunnel, eine für den Betrieb."
say "Zwei getrennte Apps, damit Produktionsschlüssel nie in Versuchen landen."
say ""
step "dev  → https://release-log-dev.czpt.de  (Tunnel, schreibt .env)"
step "prod → https://release-log.czpt.de      (Coolify, schreibt .env.production)"
say ""
ENVIRONMENT=""
while [[ "$ENVIRONMENT" != "dev" && "$ENVIRONMENT" != "prod" ]]; do
  ask ENVIRONMENT "Welche Umgebung? (dev/prod)"
done

if [[ "$ENVIRONMENT" == "dev" ]]; then
  ENV_FILE=".env"
  BASE_URL="https://release-log-dev.czpt.de"
  APP_NAME_HINT="release-log-hub-dev"
  note "Voraussetzung: scripts/setup-tunnel.sh ist gelaufen und der Tunnel läuft."
else
  ENV_FILE=".env.production"
  BASE_URL="https://release-log.czpt.de"
  APP_NAME_HINT="release-log-hub"
fi
say ""
note "Werte gehen nach $ENV_FILE"
write_env BASE_URL "$BASE_URL"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Geheimnisse erzeugen"
say "Drei Zufallswerte, erzeugt statt ausgedacht. Der erste wird gleich in"
say "GitHub eingetragen, die beiden anderen bleiben hier."
say ""
GITHUB_WEBHOOK_SECRET=$(openssl rand -hex 32)
SIGNING_KEY=$(openssl rand -hex 32)
TOKEN_ENCRYPTION_KEY=$(openssl rand -hex 32)
write_env GITHUB_WEBHOOK_SECRET "$GITHUB_WEBHOOK_SECRET"
write_env SIGNING_KEY "$SIGNING_KEY"
write_env TOKEN_ENCRYPTION_KEY "$TOKEN_ENCRYPTION_KEY"
say ""
say "Das Webhook-Secret brauchst du gleich zum Einfügen:"
printf '\n      %s%s%s\n\n' "$BOLD" "$GITHUB_WEBHOOK_SECRET" "$RESET"
note "Es steht auch in $ENV_FILE, falls du es später noch einmal brauchst."
note "TOKEN_ENCRYPTION_KEY verschlüsselt die GitHub-Nutzer-Token im Ruhezustand."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "App anlegen: Grunddaten"
say "Wir legen die App auf deinem persönlichen Konto an."
open_url "https://github.com/settings/apps/new"
say ""
step "GitHub App name:  $APP_NAME_HINT"
step "Homepage URL:     $BASE_URL"
say ""
say "Abschnitt 'Identifying and authorizing users':"
step "Callback URL:     $BASE_URL/auth/github/callback"
step "'Request user authorization (OAuth) during installation'  ANKREUZEN"
step "'Expire user authorization tokens'                        ANGEKREUZT LASSEN"
note "Die App legt Repos auf deinem persönlichen Konto an. Das geht nur mit"
note "einem Nutzer-Token, deshalb ist die Nutzer-Autorisierung Pflicht."
note "Ablaufende Token bedeuten Refresh-Token statt unbefristeter Token."
say ""
say "Abschnitt 'Webhook':"
step "'Active'          ANKREUZEN"
step "Webhook URL:      $BASE_URL/webhook"
step "Secret:           das Webhook-Secret aus Stufe 2 einfügen"
say ""
say "Ganz unten:"
step "'Where can this GitHub App be installed?' → Only on this account"
say ""
warn "Noch NICHT auf 'Create GitHub App' klicken — erst die nächste Stufe."
pause "Enter, wenn alle Felder oben stehen"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "App anlegen: Berechtigungen und Events"
say "Immer noch dasselbe Formular, Abschnitt 'Permissions'."
say ""
say "Repository permissions — genau diese drei:"
step "Administration    → Read and write   (Repos anlegen)"
step "Contents          → Read and write   (Dateien lesen und committen)"
step "Metadata          → Read-only        (ist Pflicht, meist vorausgewählt)"
say ""
say "Abschnitt 'Subscribe to events' — genau diese drei:"
step "Push"
step "Repository"
step "Member"
say ""
note "installation, installation_repositories und github_app_authorization"
note "stehen dort NICHT: die bekommt jede App automatisch, man kann sie nicht"
note "abonnieren. Suche also nicht danach."
say ""
step "Jetzt 'Create GitHub App' klicken."
pause "Enter, wenn die App angelegt ist"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "App-ID und Client-ID"
say "Du stehst jetzt auf der Einstellungsseite der neuen App."
say "Beide Werte stehen oben im Abschnitt 'About'."
say ""
step "'App ID' — eine Zahl"
ask GITHUB_APP_ID "App ID:"
step "'Client ID' — beginnt mit Iv1. oder Iv23"
ask GITHUB_CLIENT_ID "Client ID:"
write_env GITHUB_APP_ID "$GITHUB_APP_ID"
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Client-Secret"
say "Auf derselben Seite, Abschnitt 'Client secrets'."
say ""
step "'Generate a new client secret' klicken"
step "Den Wert kopieren — er wird nur einmal angezeigt"
say ""
ask_secret GITHUB_CLIENT_SECRET "Client secret einfügen (bleibt unsichtbar):"
if [[ -z "$GITHUB_CLIENT_SECRET" ]]; then
  warn "Leer geblieben. Ohne Client-Secret gibt es keine Anmeldung."
  SKIPPED+=("GITHUB_CLIENT_SECRET in $ENV_FILE nachtragen")
else
  write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Privater Schlüssel"
say "Der Schlüssel signiert das JWT, mit dem die App Installations-Token holt."
say "Ganz unten auf der Einstellungsseite, Abschnitt 'Private keys'."
say ""
step "'Generate a private key' klicken — die .pem-Datei lädt herunter"
say ""
PEM_GUESS=$(ls -t "$HOME/Downloads"/*.private-key.pem 2>/dev/null | head -n1 || true)
if [[ -n "$PEM_GUESS" ]]; then
  note "Gefunden: $PEM_GUESS"
  say ""
fi
PEM_PATH=""
while [[ ! -f "$PEM_PATH" ]]; do
  if [[ -n "$PEM_GUESS" ]]; then
    printf '  %sPfad zur .pem-Datei%s %s[Enter nimmt die gefundene]%s ' \
      "$BOLD" "$RESET" "$DIM" "$RESET"
  else
    printf '  %sPfad zur .pem-Datei:%s ' "$BOLD" "$RESET"
  fi
  read -r PEM_PATH || true
  PEM_PATH="${PEM_PATH/#\~/$HOME}"
  [[ -z "$PEM_PATH" && -n "$PEM_GUESS" ]] && PEM_PATH="$PEM_GUESS"
  [[ -f "$PEM_PATH" ]] || warn "Da liegt keine Datei. Noch einmal."
done

if ! grep -q "BEGIN RSA PRIVATE KEY\|BEGIN PRIVATE KEY" "$PEM_PATH"; then
  warn "Das sieht nicht nach einem PEM-Schlüssel aus. Trotzdem übernommen."
fi

# Base64 in eine Zeile: ein PEM überlebt keine .env-Zeile im Original.
PRIVATE_KEY_B64=$(base64 < "$PEM_PATH" | tr -d '\n')
write_env GITHUB_APP_PRIVATE_KEY "$PRIVATE_KEY_B64"
note "Als base64 abgelegt, weil ein mehrzeiliges PEM keine .env-Zeile ist."
note "Beim Lesen: Buffer.from(process.env.GITHUB_APP_PRIVATE_KEY, 'base64')"
say ""
if confirm "Heruntergeladene Datei löschen? ($PEM_PATH)"; then
  rm -f "$PEM_PATH"
  note "Gelöscht. Der Schlüssel steht jetzt nur noch in $ENV_FILE."
else
  warn "Datei bleibt liegen — sie gehört nicht in den Download-Ordner."
  SKIPPED+=("$PEM_PATH von Hand löschen")
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Installieren und Restwerte"
say "Zuletzt die App auf deinem Konto installieren und drei Werte setzen."
say ""
step "Links 'Install App', dann bei deinem Konto auf 'Install'"
step "'Only select repositories' wählen und die Log-Repos angeben —"
step "oder 'All repositories', wenn die App neue anlegen können soll"
open_url "https://github.com/settings/apps/$APP_NAME_HINT/installations"
note "Führt der Link ins Leere, heißt die App anders — dann links im Menü."
pause "Enter, wenn die App installiert ist"
say ""
ask ADMIN_LOGINS "GitHub-Logins mit Adminrecht, kommagetrennt:"
write_env ADMIN_LOGINS "$ADMIN_LOGINS"
if [[ "$ENVIRONMENT" == "dev" ]]; then
  write_env DB_PATH "./release-log.sqlite"
  write_env PORT "8080"
else
  write_env DB_PATH "/data/release-log.sqlite"
  note "PORT setzt Coolify selbst — hier keiner."
fi

finish

printf '  %sNächster Schritt%s\n' "$BOLD" "$RESET"
if [[ "$ENVIRONMENT" == "dev" ]]; then
  note "  Tunnel starten, dann der Spike:"
  note "    cloudflared tunnel --config scripts/cloudflared-release-log-dev.yml run"
else
  note "  In Coolify dieselben Werte als Umgebungsvariablen hinterlegen"
  note "  und ein Volume für DB_PATH anlegen."
fi
printf '\n'
